version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: dragon-nest-db
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - nest_network

  redis:
    image: redis:latest
    container_name: redis_nestjs
    restart: always
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - redis-data:/data
    networks:
      - nest_network
    command: ['redis-server', '--appendonly', 'yes']

volumes:
  postgres-data:
  redis-data:

networks:
  nest_network:
