import { NestEnum } from 'src/shared/enums/nests'
import {
  bdmOneToOnePng,
  bdmPng,
  bdnOneToOnePng,
  bdnPng,
  ddnOneToOnePng,
  ddnPng,
  pheonixOneToOnePng,
  pheonixPng,
  rdmOneToOnePng,
  rdmPng,
  rdnOneToOnePng,
  rdnPng,
  tcnOneToOnePng,
  tcnPng,
} from './photo-links'
import { RareHexEnum } from 'src/shared/enums/rare-color'

export const nestInfoMap = {
  [NestEnum.VN]: {
    emoji: '1353035459831398581',
    name: 'Volcano Nest',
    description: '',
    imgUrl: pheonixPng,
    imgOneToOneUrl: pheonixPng,
    color: RareHexEnum.EPIC,
  },
  [NestEnum.TCN]: {
    emoji: '1352121604905242735',
    name: 'Thrid Core Nest',
    description: '',
    imgUrl: tcnPng,
    imgOneToOneUrl: tcnOneToOnePng,
    color: RareHexEnum.EPIC,
  },
  [NestEnum.VON]: {
    emoji: '1352121603495952405',
    name: 'Volcano Order Nest',
    description: '',
    imgUrl: pheonixPng,
    imgOneToOneUrl: pheonixOneToOnePng,
    color: RareHexEnum.EPIC,
  },
  [NestEnum.BDM]: {
    emoji: '1352121600597819392',
    name: 'Black Dragon Memory',
    description: '',
    imgUrl: bdmPng,
    imgOneToOneUrl: bdmOneToOnePng,
    color: RareHexEnum.UNIQUE,
  },
  [NestEnum.RDM]: {
    emoji: '1352121612794855457',
    name: 'Red Dragon Memory',
    description: '',
    imgUrl: rdmPng,
    imgOneToOneUrl: rdmOneToOnePng,
    color: RareHexEnum.UNIQUE,
  },
  [NestEnum.BDN]: {
    emoji: '1352121614795411498',
    name: 'Black Dragon Nest',
    description: '',
    imgUrl: bdnPng,
    imgOneToOneUrl: bdnOneToOnePng,
    color: RareHexEnum.UNIQUE,
  },
  [NestEnum.DDN]: {
    emoji: '1352121618088071270',
    name: 'Desert Dragon Nest',
    description: '',
    imgUrl: ddnPng,
    imgOneToOneUrl: ddnOneToOnePng,
    color: RareHexEnum.UNIQUE,
  },
  [NestEnum.RDN]: {
    emoji: '1352121616615739402',
    name: 'Red Dragon Nest',
    description: '',
    imgUrl: rdnPng,
    imgOneToOneUrl: rdnOneToOnePng,
    color: RareHexEnum.UNIQUE,
  },
  [NestEnum.BDN_HC]: {
    emoji: '1353028827647049781',
    name: 'Black Dragon Nest',
    description: '',
    imgUrl: bdnPng,
    imgOneToOneUrl: bdnOneToOnePng,
    color: RareHexEnum.LEGEND,
  },
  [NestEnum.DDN_HC]: {
    emoji: '1353028825428005036',
    name: 'Desert Dragon Nest',
    description: '',
    imgUrl: ddnPng,
    imgOneToOneUrl: ddnOneToOnePng,
    color: RareHexEnum.LEGEND,
  },
  [NestEnum.RDN_HC]: {
    emoji: '1353028822487793734',
    name: 'Red Dragon Nest',
    description: '',
    imgUrl: rdnPng,
    imgOneToOneUrl: rdnOneToOnePng,
    color: RareHexEnum.LEGEND,
  },
}
